import { useState } from 'react'
import { createConfiguredGame, validateSetup } from '../engine/setup'
import type { Category, GameSnapshot } from '../engine/types'
import { QuestionEditor } from './QuestionEditor'

export function SetupScreen({game,onChange,onBuild}:{game:GameSnapshot;onChange:(g:GameSnapshot)=>void;onBuild:()=>void}){
  const [issues,setIssues]=useState<string[]>([])
  const rebuild=(names:string[],active=game.config.activeCategoriesPerPlayer)=>{const fresh=createConfiguredGame(names,active);onChange({...fresh,id:game.id,name:game.name,config:{...fresh.config,duelDurationMs:game.config.duelDurationMs,passPenaltyMs:game.config.passPenaltyMs}})}
  const updateCategory=(changed:Category)=>onChange({...game,categories:game.categories.map(c=>c.id===changed.id?changed:c)})
  return <main className="setup"><header><p className="kicker">Host console</p><h1>Build tonight’s floor</h1><p>Answers stay in this window. Add contestants, choose equal active topics, then arrange the board.</p></header><section className="settings panel"><h2>Game settings</h2><label>Active categories per contestant<input type="number" min="1" value={game.config.activeCategoriesPerPlayer} onChange={e=>rebuild(game.players.map(p=>p.name),Math.max(1,+e.target.value))}/></label><label>Duel seconds<input type="number" min="5" value={game.config.duelDurationMs/1000} onChange={e=>onChange({...game,config:{...game.config,duelDurationMs:+e.target.value*1000}})}/></label><label>Pass penalty seconds<input type="number" min="0" value={game.config.passPenaltyMs/1000} onChange={e=>onChange({...game,config:{...game.config,passPenaltyMs:+e.target.value*1000}})}/></label></section><section className="contestants">{game.players.map((p,i)=><article className="panel" key={p.id}><label>Contestant {i+1}<input value={p.name} onChange={e=>{const name=e.target.value;onChange({...game,players:game.players.map(x=>x.id===p.id?{...x,name}:x)})}}/></label>{game.categories.filter(c=>c.ownerId===p.id).map((c,n)=><div className="category" key={c.id}><div className="category-head"><label>Category {n+1} for {p.name}<input value={c.name} onChange={e=>updateCategory({...c,name:e.target.value})}/></label><label className="check"><input type="checkbox" checked={c.active} onChange={e=>updateCategory({...c,active:e.target.checked})}/> Active tile</label></div><QuestionEditor category={c} onChange={updateCategory}/></div>)}<button type="button" className="secondary" onClick={()=>onChange({...game,categories:[...game.categories,{id:crypto.randomUUID(),ownerId:p.id,name:`${p.name} candidate`,active:false,questions:[{id:crypto.randomUUID(),text:'',answer:'',acceptedAnswers:[]}]}]})}>Add candidate category</button></article>)}</section><div className="setup-actions"><button type="button" className="secondary" onClick={()=>rebuild([...game.players.map(p=>p.name),`Contestant ${game.players.length+1}`])}>Add contestant</button><button type="button" onClick={()=>{const found=validateSetup(game);setIssues(found);if(!found.length)onBuild()}}>Build board</button></div>{issues.length>0&&<div role="alert" className="errors">{issues.map(x=><p key={x}>{x}</p>)}</div>}</main>
}
